server {
    listen 80;
    server_name localhost;

    # 1. เสิร์ฟหน้าเว็บปกติ
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location = /health {
        default_type application/json;
        return 200 '{"status":"ok"}';
    }

    location = /api/frontend/health {
        default_type application/json;
        return 200 '{"status":"ok"}';
    }
}